schema_version = "1.0.0"

id = "sound_waveform_display"
version = "2.0.1"
name = "Sound Waveform Display"
tagline = "Display selected sound waveform in timeline/dopesheet/graph"
maintainer = "Samuel Bernou"
type = "add-on"

tags = ["Animation",]
blender_version_min = "4.2.0"
license = ["SPDX:GPL-3.0-or-later"]

copyright = ["2026 Samuel Bernou",]
